# Changes here will be overwritten by Copier
_commit: v0.10.10
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: ESLint config for fohte
error_tracking: false
is_public: true
is_web_app: false
project_name: eslint-config
release_type: node
repo_id: '734939372'
repo_language: en
subpackages: []
type: node
use_release_please: true
