# Changes here will be overwritten by Copier
_commit: v0.3.1
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: ESLint config for fohte
is_public: true
project_name: eslint-config
release_type: node
type: node
use_release_please: true
