name: Validate Package Contents

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  validate-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Validate package contents
        run: node scripts/validate-package.js
